spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.110.152:5432/zq_bpm
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 16